# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c58bc1c1affe9e21abd615ed0f5b373d98311e78d3a412a40e32a93b20ff0c556ce0fc14bc62c0463a5db94d1296aaee026d1c6df8cc661bb579cab44fc95d4

test:
  secret_key_base: 285d58b8e4817649d907ecf82d208cfe4e767fdca4238f809cb6588d5842d130468f02325ea290a7b3947efd934aad6329b7bce9724ed5b80a8a428957951f58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
